name: CI

# Controls when the action will run:
# https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#filtering-for-specific-branches-tags-and-paths
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest  # container actions require GNU/Linux
    strategy:
      matrix:
        coq_version:
          - '8.13'
          - dev
        ocaml_version:
          - '4.07-flambda'
          - '4.11-flambda'
        max-parallel: 4
        fail-fast: false  # don't stop jobs if one fails
    steps:
      # See https://github.com/coq-community/docker-coq-action#readme
      # for details on docker-coq-action's syntax and provided features.
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'folder/coq-proj.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
