# See https://github.com/coq-community/docker-coq-action#readme
name: Docker CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'coqorg/coq:8.15'
          - 'coqorg/coq:8.16'
      max-parallel: 4
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-bunched.opam'
          custom_image: ${{ matrix.image }}
